apiVersion: apps/v1
kind: Deployment
metadata:
  name: starteria-backend
  namespace: starteria
  labels:
    app: starteria-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: starteria-backend
  template:
    metadata:
      labels:
        app: starteria-backend
    spec:
      containers:
      - name: backend
        image: orlandogtp/starteria-backend:v2.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          value: "postgresql://starteria:fab67f6041e7eeee60aa040cf5a094b9@starteria-db:5432/starteria_db"
        - name: JWT_SECRET
          value: "cbfac9cad703c24a93ad9f0b939e04ee97864ac5544086b231b67a48ef832f1b"
        - name: JWT_EXPIRES_IN
          value: "15m"
        - name: JWT_REFRESH_EXPIRES_IN
          value: "7d"
        - name: CORS_ORIGIN
          value: "https://starter-ia.com"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
