apiVersion: v1
kind: Service
metadata:
  name: cloudflared-tunnel
  namespace: starteria
  labels:
    app: cloudflared-tunnel
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 2000
    targetPort: metrics
  selector:
    app: cloudflared-tunnel
