import { randomUUID } from 'node:crypto';

/**
 * Test-only Project shape. Mirrors the fields most tests assert on without
 * requiring the full Prisma model — keeps factories decoupled from the
 * generated client.
 */
export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'draft' | 'active' | 'archived';
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Build a Project fixture. Fields can be overridden individually.
 *
 * @example
 *   const p = fakeProject({ status: 'active' });
 */
export function fakeProject(overrides: Partial<Project> = {}): Project {
  const now = new Date();
  return {
    id: randomUUID(),
    name: `Project ${Math.floor(Math.random() * 10_000)}`,
    description: 'A test project generated by fakeProject().',
    status: 'draft',
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}
