import { ProjectData } from './types';

export const mockProject: ProjectData = {
  id: 'starteria-001',
  nombre: 'Onboarding TI sin fricción',
  estadoProyecto: 'En experimentación',
  stepStatus: {
    1: 'Aprobado',
    2: 'Aprobado',
    3: 'En progreso',
    4: 'No iniciado',
  },
  step3: {
    status: 'En progreso',
    upstreamChanged: false,
    testCard: {
      version: 'v1',
      hipotesisRiesgosa: 'Si TI no toma ownership del flujo, la solución no será adoptada.',
      experimento: 'Piloto con formulario único para solicitud de accesos.',
      metrica: 'Tiempo desde solicitud hasta activación',
      umbralGoNoGo: 24,
      escenario: 'Ingreso de colaboradores en unidad comercial',
      conQuien: 'RRHH, TI y 5 ingresos nuevos',
      evidenciaCapturar: 'Timestamps, conteos de SLA y capturas del tablero',
      riesgosLineasRojas: 'No comprometer seguridad de permisos ni auditoría',
    },
    runs: [
      {
        id: 'run-1',
        name: 'Run #1',
        status: 'Cerrado',
        sampleType: 'cualitativo',
        sampleSize: 5,
        planCaptura: 'Entrevistas + medición de tiempos de activación.',
        evidences: [
          { id: 'ev-1', type: 'adjunto', name: 'captura-tablero.png', tag: 'tiempo' },
          { id: 'ev-2', type: 'link', name: 'Dashboard SLA', url: 'https://example.com/sla', label: 'SLA', tag: 'SLA' },
        ],
        resultado: 26,
        fuente: 'medición directa',
        learning: {
          creiamos: 'Que con formulario único bajaríamos de 24h.',
          observamos: 'Se redujo el ruido, pero dos casos quedaron sin owner.',
          aprendimos: 'El ownership explícito impacta más que el canal.',
          haremos: 'Asignar dueño por caso y checklist de traspaso RRHH -> TI.',
        },
        decision: 'Iterar',
      },
      {
        id: 'run-2',
        name: 'Run #2',
        status: 'En ejecución',
        sampleType: 'cuantitativo',
        sampleSize: 12,
        planCaptura: 'Seguimiento diario de tiempos y % de cumplimiento.',
        evidences: [{ id: 'ev-3', type: 'adjunto', name: 'conteo-dia-1.csv', tag: 'conteo' }],
        learning: {
          creiamos: '',
          observamos: '',
          aprendimos: '',
          haremos: '',
        },
      },
    ],
    changeLog: ['Se agregó owner explícito en flujo de TI.', 'Se ajustó checklist de permisos por perfil.'],
  },
  step4: {
    status: 'No iniciado',
    requiereRefrescar: true,
    story: {
      contexto: 'En onboarding, TI recibe solicitudes tarde y sin estándar.',
      problema: 'Nuevos ingresos pierden productividad por falta de accesos.',
      queProbamos: 'Piloto de solicitud unificada con seguimiento de SLA.',
      queVimos: 'Run 1 quedó sobre umbral; Run 2 sigue en ejecución.',
      queAprendimos: 'El ownership del caso define la velocidad de cierre.',
      recomendacion: 'Iterar con dueño explícito y escalar a otra célula.',
      pedidoLider: 'Validar sponsor para expandir el piloto 4 semanas más.',
    },
    onePager: {
      reto: 'Reducir demora de accesos en onboarding sin bajar seguridad.',
      metricaUmbral: 'Tiempo de activación, umbral <= 24 horas.',
      disenoExperimento: 'Piloto con formulario único, RRHH + TI.',
      runsEjecutados: 'Run 1 cerrado, Run 2 en ejecución.',
      resultados: 'Mejora parcial, aún fuera de umbral en casos con fricción de ownership.',
      aprendizajes: 'Sin dueño de caso, el flujo se estanca.',
      recomendacion: 'Iterar sobre asignación de ownership y escalar.',
      pedidoLider: 'Sponsor de operación y 1 analista TI por 4 semanas.',
    },
    manualEdits: {},
    selectedEvidenceIds: ['ev-1'],
    razones: [],
    pedidoConcreto: '',
    fechaObjetivo: '',
  },
};
